# -*- coding: utf-8 -*-
"""Snippets: Accessing files

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/accessing_files.ipynb
"""

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

"""1. Text Generation Mode using (MODEL - GPT2)"""

!from transformers import pipeline
generator = pipeline('text-generation', model='gpt2')
response = generator("What is Hugging Face,", max_length=30, num_return_sequences=1)
print(response[0]['generated_text'])

"""**2- NAMED ENTITY RECOGNITION (NER)**"""

from transformers import pipeline
ner = pipeline('ner',grouped_entities = True)
entities = ner('I am Shabhash Shaik, an QA Engineer is reputed organisation, now actively looking to update profile as AI Field')
print(entities)

"""**3 . SENTIMENT ANALYSIS**"""

!pip install transformers datasets

from transformers import pipeline
classifier = pipeline('sentiment-analysis')
result = classifier('I love Hugging Face Library very much, it is so  nice')
print(result)

from transformers import pipeline
classifier = pipeline('sentiment-analysis')
result = classifier("I have ordered cup-cakes from Star Bakery, but food is staled and i don't like it at all")
print(result)

!pip install gradio

import gradio as gr
classifier = pipeline('sentiment-analysis')
def analyze_sentiment(text):
  return classifier(text)[0]['label']

gr.Interface(fn = analyze_sentiment, inputs = "text", outputs = "text").launch()

"""**4- TEXT TO IMAGE MODEL USING DIFFSUSION PIPELINE**"""

from diffusers import StableDiffusionPipeline
import torch

model_id = "sd-legacy/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "An husband who is always blamed even though he put his full efforts to feed his family"
image = pipe(prompt).images[0]

image.save("family_man.png")

import gradio as gr
from diffusers import StableDiffusionPipeline
import torch
model_id = "sd-legacy/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

def generate_image(prompt):
  image = pipe(prompt).images[0]
  image.save(f"outputs/{prompt}.png")
  return image

gr.Interface(fn = generate_image,
             inputs = gr.Textbox(label = 'Enter your prompt',placeholder='An husband who is always blamed even though he put his full efforts to feed his family') ,
             outputs = gr.Image(type='pil',label='Generated Image'),
             title = 'Shabhash TEXT - IMAGE GENERATOR',
             description = 'Enter your prompt and see your image Generated').launch()

!nvidia-smi